# Balancing requirements
# ----------------------
# Lists reflect modes which are allowed in the output
# Remove any undesired modes
allowed_balancing: [balanced, early_game_heavy, late_game_heavy] # options: balanced, early_game_heavy, late_game_heavy
allowed_spreads: [clustered, wide_spread, mixed_spread] # options: clustered, wide_spread, mixed_spread
allowed_patterns: [single_cluster, dual_cluster, early_late_split] # options: single_cluster, dual_cluster, early_late_split, middle_only

force_starter: true

allow_not_fully_evolved: false
max_evo_stage: 3 # options: int

allow_legendaries: false
allow_duplicate_species: false

# Types
# -----

allow_dual_type: true

type_distribution: anything_goes # options: no_overlap, all_share_one_type, anything_goes

# only works when type_distribution = all_share_one_type
prescribed_type: none # options: any type (fire, water, etc.) or none

species_blacklist: [] # a comma-separated list of Pokemon species (stage 1s), each in all caps (Mr. Mime is MR.MIME, Farfetch'd is FARFETCHD, Nidoranâ™‚ is NIDORAN_M)

allowed_evo_methods:
  none: true # AKA stage 1 Pokemon
  level-up: true
  moon_stone: true
  fire_stone: true
  water_stone: true
  thunder_stone: true
  leaf_stone: true
  trade: true

#TODO add suggestions here for general cutoffs that make sense for easy mode, hard mode etc.
bst_max: none # options: integers or none
bst_min: none # options: integers or none

# party-wide coverage
ensure_hm_coverage:
  FLASH: false
  CUT: true
  STRENGTH: true
  FLY: false
  SURF: true
  DIG: false
  TELEPORT: false
  SOFTBOILED: false

allowed_acquisition_methods:
  starter: true
  walk: true
  surf: true
  old_rod: true
  good_rod: true
  super_rod: true
  poke_flute: true
  static_encounter: true
  trade: true
  gift: true
  purchase: true
  fossil_restore: true
  prize_window: true

# CLI UI
show_acquisition_details: true
show_balance_stats: true
